---
abstract: ~
author:
  - 'Cornelius <cornelius.howl@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.90'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Gearman-XS-Declare
no_index:
  directory:
    - inc
    - t
requires:
  Exporter::Lite: 0
  Gearman::XS: 0
  Gearman::XS::Worker: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
